services:
  - type: web
    name: p4-dpi-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    healthCheckPath: /api/health
    healthCheckTimeout: 30
    autoDeploy: true
