services:
  - type: web
    name: p4-dpi
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: DPI_TRAFFIC_TARGET_PACKETS
        value: '600'
    healthCheckPath: /api/health
    healthCheckTimeout: 60
    autoDeploy: true
